run:
	g++ -o elevators.out -std=c++0x -pthread elevators.cpp person.cpp elevator.cpp floor.cpp && ./elevators.out

build:
	g++ -o elevators.out -std=c++0x -pthread elevators.cpp person.cpp elevator.cpp floor.cpp
